# Numpy

Numpy:- Numpy stnds for numerical python and is the core library for numeric and scientific computing, 
    It consists of multi_dimentional array objects 


- Its an homogeneous in nature the numpy list contains single datatype
- The array which we are using will doesnot supports multi dimentional, It only allows 1(single dimention).
- So to work on multidimention arry we use 3rd party package called Numpy

### Load in NumPy (remember to pip install numpy first)

In [3]:
import numpy as np

### The Basics

In [4]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [26]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print("it's an float value=\n",b, "\n",b.dtype)  


b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]],dtype="int64")          #if you give int here it will convert in to int and gives you the flore value
print("\nit's an int value =\n",b,"\n",b.dtype)

it's an float value=
 [[9. 8. 7.]
 [6. 5. 4.]] 
 float64

it's an int value =
 [[9 8 7]
 [6 5 4]] 
 int64


In [6]:
# Get Dimension
a.ndim

1

In [11]:
# Get Shape
b.shape

(2, 3)

In [13]:
# Get Type
b.dtype

dtype('int16')

In [28]:
# Get Size
b.itemsize             # because its an integer (int8=itemsize=1,int16=2,int32=4,int64=8)    it gives only for 1 item

8

In [29]:
# Get total size, where total size(nbytes) = a.size*a.itemsize
b.nbytes     #(itemsize*size)

48

In [30]:
# Get number of elements
b.size

6

### Accessing/Changing specific elements, rows, columns, etc

In [1]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
# Get a specific element [r, c]
a[0, -1]

7

In [15]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [34]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, ::2]

array([1, 3, 5, 7])

In [4]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  2  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [11]:
import numpy as np
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
b.ndim

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


3

In [13]:
# Get specific element (work outside in)
b[0,1,1]

4

In [32]:
# replace 
b[:,1,:] = [[9,9],[8,8]]


In [33]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [40]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
import numpy as np
# All 1s matrix
a=np.ones((2,2,2), dtype='int32')
print(a)
a.ndim

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


3

In [72]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [15]:
# Any other number (full_like)
np.full_like(a, 4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [21]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.54753032, 0.41162476],
       [0.77456983, 0.22784001],
       [0.64839585, 0.81128893],
       [0.50647496, 0.37802269]])

In [17]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 5,  4,  1],
       [ 0,  3,  2],
       [-3,  2,  0]])

In [22]:
# The identity matrix
a=np.identity(3)             #identy matrix is nothing but it prints "1" diagonally
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# To print the value diagonally
np.diagonal(a)               #it gives you the values of diagonal number

array([1., 1., 1.])

In [99]:
# giving proper example by including some condition

a=np.random.randint(30,size=(3,3))()
print("printing a=\n",a)
b=np.diagonal(a)
print("\nprinting the diagonal values of a=",b)

printing a=
 [[ 5 21 29]
 [ 0  3  8]
 [22  3  1]]

printing the diagonal values of a= [5 3 1]


In [25]:
# Repeat an array                   #  it should me multi dimentional to do repeat function
a = np.array([[1,2,3]])
r1 = np.repeat(a,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [112]:
# you can use the flatten to convert any dimension in to 1 dimension
#lets take the above example
print("r1=\n",r1)
print("printing the dimension of r1=\n",r1.ndim)
r2=r1.flatten()
# Here we are going to convert the 2dimenson in to 1dimension
print("r2=\n",r2)
print("printing the converted dimension of(r1) r2=\n",r2.ndim)


r1=
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
printing the dimension of r1=
 2
r2=
 [1 2 3 1 2 3 1 2 3]
printing the converted dimension of(r1) r2=
 1


In [105]:
import numpy as np
a=np.array([1,5,9,7])
b=np.array([9,12,6,14])
np.repeat((a,b,a),(2,3,2),axis=0)

array([[ 1,  5,  9,  7],
       [ 1,  5,  9,  7],
       [ 9, 12,  6, 14],
       [ 9, 12,  6, 14],
       [ 9, 12,  6, 14],
       [ 1,  5,  9,  7],
       [ 1,  5,  9,  7]])

In [89]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [47]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
b

[1 2 3]


array([100,   2,   3])

In [48]:
a = np.array([1,2,3])
b = a
b[0] = 100

print(a)
b

[100   2   3]


array([100,   2,   3])

### Mathematics

In [49]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [55]:
a[3]+2

6

In [50]:
a + 2

array([3, 4, 5, 6])

In [102]:
a - 2

array([-1,  0,  1,  2])

In [103]:
a * 2

array([2, 4, 6, 8])

In [104]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [118]:
b = np.array([1,0,1,0])
a + b

array([1, 0, 3, 0])

In [113]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [116]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

##### Linear Algebra

In [65]:
# In matrix multiplication the number of column of first element should be equal to no of rows of the second element

#And the output of the matrix will be the no rows in first element and the number of column in the second element

a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)    #where in matrix multiplication there should be no of columns = no of rows

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [113]:
a=np.full((3,4),5)
b=np.ones((4,2),dtype="int")
print(a)
print(b)
print("\n")



c=np.matmul(a,b)
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]


[[20 20]
 [20 20]
 [20 20]]


In [115]:
# Find the determinant
#determent is only posible for square matrixe  ex:- number of rows is equal to no of columns
a=np.random.randint(20,size=(3,3))
print(a)
np.linalg.det(a)

[[15 19 14]
 [12 13 15]
 [ 6  7  1]]


186.00000000000009

##### Statistics

In [1]:
import numpy as np

In [69]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.min(stats,axis=0)

array([1, 2, 3])

In [141]:
np.max(stats, axis=1)

array([3, 6])

In [143]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [73]:
# If  you are performing the reshape operation then you have to consider that the size=to the multiple of shape


before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [122]:
a=np.array([[4,6,6,99],[4,9,5,32]])
print("a=\n",a)
a=a.flatten()
print("\nbefore reshape=",a)


a=a.reshape((2,2,2))
print("\nafter reshape=\n",a)

a=
 [[ 4  6  6 99]
 [ 4  9  5 32]]

before reshape= [ 4  6  6 99  4  9  5 32]

after reshape=
 [[[ 4  6]
  [ 6 99]]

 [[ 4  9]
  [ 5 32]]]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print('Before Reshaping =',arr)
print('After Reshaping =\n',newarr)

Before Reshaping = [ 1  2  3  4  5  6  7  8  9 10 11 12]
After Reshaping =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [125]:
#vertical stack(vstack)

# You can do vertical staking for one vector (vstack)
# If you want to perform for more than one vector you want to mention in the list
# If you are vertically stacking more than one array the size of array should be same

a=np.array([5,6,96,36,8,3])
np.vstack(a)

array([[ 5],
       [ 6],
       [96],
       [36],
       [ 8],
       [ 3]])

In [11]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [5]:
# Horizontal stack (hstack)

# # You can do horizontal staking for one vector (hstack)
# If you want to perform for more than one vector you want to mention in the list
# If you are horizontally stacking more than one array the size of array may be different not an issue

a=np.array([[4,6,6,99],[5,5,9,62]])
print(a)

f=a.flatten()
print("flatten=",f)

h=np.hstack(a)
print("hstack=",h)

[[ 4  6  6 99]
 [ 5  5  9 62]]
flatten= [ 4  6  6 99  5  5  9 62]
hstack= [ 4  6  6 99  5  5  9 62]


In [36]:
# Horizontal  stack 
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2,h2])

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [42]:

# a=np.genfromtxt(r"C:\Users\JEEVAN\Downloads\data.txt",delimiter=",")      # if use r no need to change the shash(/)
filedata = np.genfromtxt("C:/Users/JEEVAN/data.txt", delimiter=',')           # to copy the path file (go to location and shift right button)
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [196]:
(~((filedata > 50) & (filedata < 100)))
#((~)it is not operation)

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [49]:
data=np.genfromtxt("C:/Users/JEEVAN/data.txt",delimiter=",")
data=data.astype("int32")
print(data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [58]:
#it operate same like by giving the index no it gives you the value

f=data[data>50]
print(f)


[196  75 766  75  55 999  78  76  88]


In [62]:
#if any one value in a column is greater than 50 it prints true
np.any(data>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [64]:
#all the value in a column should be greater than 50 
np.all(data>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [65]:
#if any one value in a row is greater than 50 it prints true
np.any(data>50,axis=1)

array([ True,  True,  True])

In [66]:
#all the value in a row should be greater than 50 
np.all(data>50,axis=1)

array([False, False, False])

In [60]:
a=(~(data>50)&(data<150))
print(a)

[[ True  True  True  True False False  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True False False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True False  True  True  True False  True  True  True
   True  True  True  True False False]]
