In [101]:
import numpy as np
import  pandas as pd

### 1. Write a program to check whether an year entered by an user is leap year or not

In [2]:
check_year = int(input("Check The Year: "))
print("Enter the year:" , check_year)
if(check_year % 4) == 0:
    if(check_year % 100) == 0:
        if(check_year % 400) == 0:
            print(check_year, "Is A LEAP YEAR!")
        else:
            print(check_year, "IS NOT A NOT LEAP YEAR!")
    else:
        print(check_year, "IS A LEAP YEAR!")
else:
    print(check_year, "IS NOT A LEAP YEAR!")
            

Enter the year: 2020
2020 IS A LEAP YEAR!


### 2. Take a string containing punctuation marks as an input from user and write a program to remove all the  punctuation marks from a string

In [3]:
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
input_str = str(input("Enter THE STRING: "))
print(input_str)
new_str = ""
for char in input_str:
    if char not in punc:
        new_str += char
print(new_str)

abcdd
abcdd


### 3. Take two separate numbers as input from the user and Write a program to swap 2 numbers without using temporary variable

In [4]:
num1 = int(input("Number #1"))
num2 = int(input("Number #2"))
print("First Number : ", num1)
print("Second Number: ", num2)
num1 = num1 + num2 # num1 = 2 + 3 = 5
num2 = num1 - num2 # num2 = 5 - 3 = 2
num1 = num1 - num2 # num1 = 5 - 2 = 3
print("Swapped Number#1 :", num1)
print("Swapped Number#2 :", num2)

First Number :  3
Second Number:  4
Swapped Number#1 : 4
Swapped Number#2 : 3


### 4. Write a program to print product of following variables
 integer = 10 
 string = "15"

In [5]:
integer = 10
string = "15"
str_num = int(string)
product = integer * str_num
print("Product :" , product)

Product : 150


### 5. Write a program to print following pattern -
<br>a
<br>b c
<br>d e f
<br>g h i j
<br>k l m n o
<br>p q r s t u

In [6]:
char = 97
inputC = int(input("Enter N: "))
for i in range(0, inputC):
    for j in range(0, i + 1):
        print(chr(char), end =" ")
        char += 1
    
    print()

a 


### 6. Write a program to print tables from 2 to n, where n is provided by user

In [7]:
tableN = int(input("ENTER N FOR INPUT: "))
for n in range(2, tableN + 1):
    print("TABLE OF" , n)
    for i in range(1, 11):
        print(n, ' X ', i, " = ", n*i)
    print()

TABLE OF 2
2  X  1  =  2
2  X  2  =  4
2  X  3  =  6
2  X  4  =  8
2  X  5  =  10
2  X  6  =  12
2  X  7  =  14
2  X  8  =  16
2  X  9  =  18
2  X  10  =  20

TABLE OF 3
3  X  1  =  3
3  X  2  =  6
3  X  3  =  9
3  X  4  =  12
3  X  5  =  15
3  X  6  =  18
3  X  7  =  21
3  X  8  =  24
3  X  9  =  27
3  X  10  =  30


### 7. Write a program to read height (in centimeters) from user and then convert it to feet and inches

In [8]:
input_height = int(input("ENTER YOUR HEIGHT(in centimetres) :"))
# 1 cm = .032 cm
# 1 cm = .393 inch   

height_feet = round((input_height / 30.48), 1)
height_inch = round((input_height / 2.54) , 1) 
print(height_feet, "FEET")
print(height_inch, "INCH")

10.9 FEET
131.1 INCH


### 8. Write a program to print following pattern
                                                *
                                                * * 
                                                * * *
                                                * *
                                                *

In [9]:
N = int(input("ENTER THE NUMBER: "))
for i in range(0, N-1):
    for j in range(i + 1):
        print("*" , end=" ")
    print()
for i in range(1, N+1):
    print("*" , end=" ")
print()
for i in range(N-1, 0, -1): # start, stop, step 
    for j in range(i, 0, -1):
        print("*" , end=" ")
    print()

* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 
* * * * * * * 
* * * * * * * * 
* * * * * * * * * 
* * * * * * * * * * 
* * * * * * * * * * * 
* * * * * * * * * * * * 
* * * * * * * * * * * * * 
* * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
* * * * * * * * * * * * * * * * * * * * 

### 9. Below list contains age and name of five students. Convert the list into a dictionary such that the name is taken as key and the age before their name is taken as thier respective value in the dictionary

students = [26,'Jon',34,'Roger',13,'Jessica',24,'Monica',65,'Ashton']
Output: {'Jon':26, 'Roger':34, 'Jessica':13, 'Monica':24, 'Ashton':65}

In [10]:
students = [26,'Jon',34,'Roger',13,'Jessica',24,'Monica',65,'Ashton']
dict1 = {}
for i in range(0, len(students), 2):
    dict1[students[i + 1]] = students[i]
print(dict1)

{'Jon': 26, 'Roger': 34, 'Jessica': 13, 'Monica': 24, 'Ashton': 65}


### 10. Write a program to check whether two strings, taken from user, are anagram or not

In [11]:
string1 = str(input("ENTER STRING 1:"))
string2 = str(input("ENTER STRING 2:"))

if sorted(string1.lower()) == sorted(string2.lower()):
    print("STRINGS ARE ANAGRAM!")
else:
    print("STRINGS ARE NOT ANAGRAM!")

STRINGS ARE NOT ANAGRAM!


### 11. Write a program that sorts all the elements of the list according to the first letter, irrespective of their cases (uppercase or lowercase). Note: Do not use any inbuilt sorting function

In [12]:
names = ["dakshay", "camaro", "anubhav", "elliderson", "dante"]
for i in range(len(names)):
    for j in range(i+1, len(names)):
        if names[i][0] > names[j][0]:
            names[i], names[j] = names[j], names[i]
print(names)

['anubhav', 'camaro', 'dakshay', 'dante', 'elliderson']


### 12. Write a program that prints a list of sour fruits from the below tuple:
<br>fruits = (('Lemon','sour'), ('DragonFruit', 'Sweet'), ('Grapes','soUr'), ('Kiwi','Sour'), ('Apples','sweet'), ('Orange','sour'), ('Blueberries','sweet'), ('Limes','Sour') )

In [13]:
fruits = (('Lemon','sour'), ('DragonFruit', 'Sweet'), ('Grapes','soUr'), ('Kiwi','Sour'), ('Apples','sweet'), ('Orange','sour'), ('Blueberries','sweet'), ('Limes','Sour'))

output_fruit = []
for fruit in fruits:
    if fruit[1].lower() == "sour":
        output_fruit.append(fruit[0])
print("Sour Fruits:", output_fruit)        

Sour Fruits: ['Lemon', 'Grapes', 'Kiwi', 'Orange', 'Limes']


### 13. Given below are the list of positive and negative words. Also a list of tweets is provided. Separate out the positive and negative comments
<br>positive = ['good','awesome', 'best', 'nice']

<br>negative = ['worst','awful', 'bad']

<br>tweets = ['This government policies are good', 
'bad implementation', 'The way he played showed that he is one of the best players in the world', 'Her acting in the play was awesome', 'The wine tastes awful', 'It's nice to hear this little kid's laugh']

In [14]:
positive = ["good","awesome", "best", "nice"]
negative = ["worst","awful", "bad"]
tweets = ['This government policies are good', 'bad implementation', 'The way he played showed that he is one of the best players in the world', 'Her acting in the play was awesome', 'The wine tastes awful', 'It’s nice to hear this little kid’s laugh']

good_tweets = []
bad_tweets = []

for tweet in tweets:
    for good in positive:
        if good in tweet:
            good_tweets.append(tweet)
    for bad in negative:
        if bad in tweet:
            bad_tweets.append(tweet)
print("GOOD TWEETS ARE:", good_tweets)  
print()
print("BAD TWEETS ARE:", bad_tweets)

GOOD TWEETS ARE: ['This government policies are good', 'The way he played showed that he is one of the best players in the world', 'Her acting in the play was awesome', 'It’s nice to hear this little kid’s laugh']

BAD TWEETS ARE: ['bad implementation', 'The wine tastes awful']


### 14. Write a program that performs multiplication of the following two matrix

In [15]:
X = np.array([[1,2,3],
    [4 ,5,6],
    [7 ,8,9]])

Y = np.array([[1,8,1],
    [3,7,3],
    [4,5,9]])

multi = X.dot(Y)
print(multi)

[[ 19  37  34]
 [ 43  97  73]
 [ 67 157 112]]


### 16.  Write a program to display the subjects for which the scores are between 300 and 500 (inclusive) in the given dataframe
Use the dataframe given below:
Subject Score
Maths 345
Physics 432
Chemistry 456
Biology 234
Geology 254


In [60]:
result = {'Subject': ['Maths', 'Physics', 'Chemistry', 'Biology', 'Geology'], 'Score': [345, 432, 456, 234, 254]}
df = pd.DataFrame(data=result)
print('Subjects for which marks are between 300 and 500:\n', df['Subject'] [df['Score'].between(300, 500)])

Subjects for which marks are between 300 and 500:
 0        Maths
1      Physics
2    Chemistry
Name: Subject, dtype: object


### 17. Write a program to find numbers between 10000 to 20000 from a given array
**Use the list given below:**

Sales = [1432,143223,2043332,1642357,54327,754338,12459,75435,224454,1433,12447,25532,86674,74338,12678]

In [77]:
Sales = [1432,143223,2043332,1642357,54327,754338,12459,75435,224454,1433,12447,25532,86674,74338,12678]
for i in Sales:
    if 20000 >= i >= 10000:
        print(i)

12459
12447
12678


In [112]:
leaderboard = [['Joy', 115], ['Mia', 451], ['Karan', 341], ['Tom', 84]]
leaderboard_df = pd.DataFrame(data=leaderboard, columns=['Name', 'Rank'])
print('Data Frame: \n\n', leaderboard_df)
print('Sorted Data Frame\n', leaderboard_df.sort_values(by=['Rank']))

Data Frame: 

     Name  Rank
0    Joy   115
1    Mia   451
2  Karan   341
3    Tom    84
Sorted Data Frame
     Name  Rank
3    Tom    84
0    Joy   115
2  Karan   341
1    Mia   451


In [125]:
age = [[1,'Mia', 47, 1], [2, 'Sara', 38, 1] , [3, 'Joy', 47, 0], [4, 'Karan', 41, 0]]
df = pd.DataFrame(age, columns=['Id','Name', 'Age', 'Gender'])
df['Gender'] = df['Gender'].map({0:'M', 1:'F'})
(df)

Id   Name  Age Gender
0   1    Mia   47      F
1   2   Sara   38      F
2   3    Joy   47      M
3   4  Karan   41      M