In [1]:
import numpy as np

In [2]:
age = [18, 23, 40, 31, 28]
age_arr = np.array(age)
print(age_arr)
print(type(age_arr))

[18 23 40 31 28]
<class 'numpy.ndarray'>


In [3]:
np.random.random(size = 20)

array([0.39858583, 0.88133039, 0.68683143, 0.03786219, 0.44915532,
       0.68226684, 0.1033865 , 0.12382335, 0.71204127, 0.07643994,
       0.48371736, 0.79304334, 0.99432026, 0.89507441, 0.93741719,
       0.10210113, 0.22165577, 0.30446312, 0.5436899 , 0.58545803])

In [4]:
np.random.rand(2,4)

array([[0.85886783, 0.23471001, 0.74062787, 0.37951175],
       [0.23502415, 0.33377318, 0.32205991, 0.39883796]])

In [5]:
np.random.randn(3,3)

array([[-0.00274981,  0.06643864, -0.26822215],
       [-0.51342983, -0.46198738,  1.00451591],
       [ 0.98522564,  0.42781722, -0.13088321]])

In [6]:
np.random.randint(2,9)

2

In [7]:
np.random.randint(1,100,10)

array([85, 18, 18, 69, 79,  7, 87, 78,  6,  1])

In [8]:
np.arange(10,40,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [9]:
np.linspace(1,100,10)
# np.linspace(1,100,10, dtype=int)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [10]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [12]:
# np.empty((3,3))
np.empty((3,3), dtype=int)

array([[      0,       1,       0],
       [    477,    1204,       0],
       [    768,     477, 6815842]])

In [13]:
np.full((3,3,), fill_value=24)

array([[24, 24, 24],
       [24, 24, 24],
       [24, 24, 24]])

In [14]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.eye(N=5,M=5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [16]:
nums = np.array([(10,20,30), (12, 34, 56)])
print(nums.shape)
print(nums.size)
print(nums.dtype)
print(nums.ndim)

(2, 3)
6
int32
2


In [17]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
emp = np.array([('Charles',18), ('Logan',20), ('Jessica', 34)])
print(emp, '\n')
emp_reshaped = emp.reshape(6,1)
print(emp_reshaped)

[['Charles' '18']
 ['Logan' '20']
 ['Jessica' '34']] 

[['Charles']
 ['18']
 ['Logan']
 ['20']
 ['Jessica']
 ['34']]


In [19]:
print(emp[0])
print(emp[-1])
print(emp[0][1])

['Charles' '18']
['Jessica' '34']
18


In [20]:
weight = np.array([73, 68, 55.5, 43, 92, 66])
print(weight[3:5])
print(weight[::3])
print(weight[:3])

[43. 92.]
[73. 43.]
[73.  68.  55.5]


In [21]:
age = np.array([[73,68,54], [21,36,19]])
print(age[0, 0:2])
print(age[1, 1:3])

[73 68]
[36 19]


In [22]:
odd_num = np.array([1,5,9,15])
even_num = np.array([2,6,12,26])
sum = odd_num + even_num
sub = odd_num - even_num
multiplication = odd_num * 2
print(sum)
print(sub)
print(multiplication)

[ 3 11 21 41]
[ -1  -1  -3 -11]
[ 2 10 18 30]


In [23]:
#Hamadard Product
n1 = np.array([[1,0,2], [4,-2,3]])
n2 = np.array([[4,0,1], [2,3,0]])
prod = n1 * n2
print(n1, '\n')
print(n2, '\n')
print(prod)

[[ 1  0  2]
 [ 4 -2  3]] 

[[4 0 1]
 [2 3 0]] 

[[ 4  0  2]
 [ 8 -6  0]]


In [24]:
#Matrix Multiplication
m1 = np.array([[1,0,2], [4,-2,3]])
m2 = np.array([[4,0],[2,3], [1,4]])

multi = m1.dot(m2) 
multi2 = m2.dot(m1)
print(multi2)
print()
print(multi)

[[ 4  0  8]
 [14 -6 13]
 [17 -8 14]]

[[ 6  8]
 [15  6]]


In [25]:
salary = np.array([100000, 2000, 45000, 980000, 1000, 75500])
print("Max salary:", salary.max())
print("Min salary:", salary.min())
print("Variance:", salary.var())
print("Standard Deviation:", salary.std())

Max salary: 980000
Min salary: 1000
Variance: 122788034722.22223
Standard Deviation: 350411.23658099526


In [26]:
nums = np.array([1,2,3,4,5])
print(np.square(nums))
print(np.power(nums,3))

[ 1  4  9 16 25]
[  1   8  27  64 125]


In [27]:
print(emp)
print(emp.shape, '\n')
print(np.transpose(emp))
print(np.transpose(emp).shape)

[['Charles' '18']
 ['Logan' '20']
 ['Jessica' '34']]
(3, 2) 

[['Charles' 'Logan' 'Jessica']
 ['18' '20' '34']]
(2, 3)


In [28]:
#concatenate two 1D arrays
print(odd_num, even_num)
all_nums = np.concatenate([odd_num, even_num])
print(all_nums)

[ 1  5  9 15] [ 2  6 12 26]
[ 1  5  9 15  2  6 12 26]


In [29]:
#concatenate two 2D arrays
data_scientists = np.array([('Charles',18), ('Logan',20), ('Jessica', 34)])
consultants = np.array([('Jean', 21), ('Phoenix', 20)])
employees = np.concatenate([data_scientists, consultants])
print(employees)

[['Charles' '18']
 ['Logan' '20']
 ['Jessica' '34']
 ['Jean' '21']
 ['Phoenix' '20']]


In [30]:
num_array = np.array([[1,3,5,7],[2,4,6,8]])
print(np.ndarray.flatten(num_array))

[1 3 5 7 2 4 6 8]


In [31]:
num = np.arange(1,13)
print(num, '\n')
new_num = num.reshape(3,4)
print(new_num)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
a = np.arange(1,7)
new_a = np.vstack(a)
print(a, a.shape)
print()
print(new_a, new_a.shape)
print()
print(a[0], new_a[0])

[1 2 3 4 5 6] (6,)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)

1 [1]


In [33]:
v1 = np.random.randint(2,8,4)
v2 = np.random.randint(3,9,4)
print(v1, v2, '\n')
print(np.vstack([v1, v2, v2, v1]))

[4 5 7 2] [5 5 8 3] 

[[4 5 7 2]
 [5 5 8 3]
 [5 5 8 3]
 [4 5 7 2]]


In [34]:
v3 = np.array([[4,4,5,5], [4,3,7,6]])
print(v3, '\n')
print(np.vstack([v3, v3]), '\n')
print(np.vstack([v3[1], v3[0]]))

[[4 4 5 5]
 [4 3 7 6]] 

[[4 4 5 5]
 [4 3 7 6]
 [4 4 5 5]
 [4 3 7 6]] 

[[4 3 7 6]
 [4 4 5 5]]


In [35]:
a = np.array([[1,4,6], [5,7,8]])
print(np.hstack(a))

[1 4 6 5 7 8]


In [36]:
h1 = np.array([[1,4,6], [5,7,8]])
h2 = np.array([[2,9,3], [17,31,26]])
print(np.hstack([h1, h2, h1]))

[[ 1  4  6  2  9  3  1  4  6]
 [ 5  7  8 17 31 26  5  7  8]]


In [37]:
for i in data_scientists:
    print(i)
print()
for i in data_scientists:
    for j in i:
        print(j)

['Charles' '18']
['Logan' '20']
['Jessica' '34']

Charles
18
Logan
20
Jessica
34
